Models/Case.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FinalProject.Models
{
    public class Case : IComparable<Case>
    {
        [Key]
        public int id { get; set; }
        [ForeignKey("Company")]
        public int companyId { get; set; }
        public Company? company { get; set; }
        [ForeignKey("DangerLevel")]
        public int levelId { get; set; }
        public DangerLevel? level { get; set; }
        public DateTime? requiredDate { get; set; }
        public int? assedHours { get; set; }
        public int CompareTo(Case? other)
        {
            if (other == null)
            {
                // If other is null, this instance is greater.
                return 1;
            }

            if (requiredDate.HasValue && other.requiredDate.HasValue)
            {
                // Compare based on the absolute difference between required dates and the current date.
                TimeSpan diffThis = requiredDate.Value - DateTime.Now;
                TimeSpan diffOther = other.requiredDate.Value - DateTime.Now;

                return diffThis.CompareTo(diffOther);
            }
            else if (requiredDate.HasValue)
            {
                // If other has no required date but this instance has, this instance is greater.
                return -1;
            }
            else if (other.requiredDate.HasValue)
            {
                // If this instance has no required date but other has, other is greater.
                return 1;
            }
            else
            {
                // If neither has a required date, consider them equal.
                return 0;
            }
        }
    }
}

Controllers/CaseController.cs
using FinalProject.Interfaces;
using FinalProject.Models;
using FinalProject.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers
{
    public class CaseController : Controller
    {
        private readonly ICaseRepository _caseRepository;
        private readonly ICompanyRepository _companyRepository;
        private readonly IDangerLevelRepository _levelRepository;
        public CaseController(ICaseRepository caseRepository, ICompanyRepository companyRepository, IDangerLevelRepository dangerLevelRepository)
        {
            _caseRepository = caseRepository;
            _companyRepository = companyRepository;
            _levelRepository = dangerLevelRepository;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Case> cases = await _caseRepository.GetAll();
            return View(cases);
        }
        public async Task<IActionResult> Details(int id)
        {
            Case myCase = await _caseRepository.GetByIdAsync(id);
            return View(myCase);
        }
        public async Task<IActionResult> Create()
        {
            CreateCaseViewModel viewModel = new CreateCaseViewModel();
            viewModel.companies = await _companyRepository.GetAll();
            viewModel.dangerLevels = await _levelRepository.GetAll();
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateCaseViewModel caseVm)
        {
            if (ModelState.IsValid)
            {
                Company company = await _companyRepository.GetByIdAsync(caseVm.companyId);
                DangerLevel dangerLevel = await _levelRepository.GetByIdAsync(caseVm.dangerId);
                Case myCase = new Case();
                myCase.companyId = caseVm.companyId;
                myCase.company = company;
                myCase.levelId = caseVm.dangerId;
                myCase.level = dangerLevel;
                myCase.requiredDate = caseVm.reqiredDate;
                myCase.assedHours = caseVm.assedHours;
                _caseRepository.Add(myCase);
                return RedirectToAction("Index");
            }
            return View(caseVm);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Case myCase = await _caseRepository.GetByIdAsync(id);
            if (myCase == null)
            {
                return View("Error");
            }

            EditCaseViewModel caseVM = new EditCaseViewModel
            {
                id = myCase.id,
                reqiredDate = myCase.requiredDate,
                dangerId = myCase.levelId,
                companyId = myCase.companyId,
                assedHours = myCase.assedHours
            };
            caseVM.companies = await _companyRepository.GetAll();
            caseVM.dangerLevels = await _levelRepository.GetAll();
            return View(caseVM);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditCaseViewModel caseVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed Edit");
                return View("Edit", caseVM);
            }
            Company company = await _companyRepository.GetByIdAsync(caseVM.companyId);
            DangerLevel dangerLevel = await _levelRepository.GetByIdAsync(caseVM.dangerId);
            Case myCase = new Case
            {
                id = caseVM.id,
                requiredDate = caseVM.reqiredDate,
                levelId = caseVM.dangerId,
                level = dangerLevel,
                company = company,
                companyId = caseVM.companyId,
                assedHours = caseVM.assedHours
            };
            _caseRepository.Update(myCase);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Case caseDetails = await _caseRepository.GetByIdAsync(id);
            if (caseDetails == null)
            {
                return View("Error");
            }
            return View(caseDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteRole(int id)
        {
            Case caseDetails = await _caseRepository.GetByIdAsync(id);
            if (caseDetails == null)
            {
                return View("Error");
            }
            _caseRepository.Delete(caseDetails);
            return RedirectToAction("Index");
        }
    }
}

Views/Case/Create.cshtml
@using FinalProject.ViewModel
@using FinalProject.Repository
@model CreateCaseViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post" asp-action="Create">
    <div class="form-group">
        <label asp-for="reqiredDate">reqiredDate</label>
        <input asp-for="reqiredDate" class="form-control" placeholder="Enter reqiredDate">
    </div>
    <div class="form-group">
        <label asp-for="assedHours">assedHours</label>
        <input asp-for="assedHours" class="form-control" placeholder="Enter assedHours">
    </div>
    <div class="form-group">
        <select asp-for="companyId">
            <option value="">-- Select Company --</option>
            @foreach (var item in Model.companies)
            {
                <option value="@item.id">@item.name</option>
            }
        </select>
    </div>
    <div class="form-group">
        <select asp-for="dangerId">
            <option value="">-- Select DangerLevel --</option>
            @foreach (var item in Model.dangerLevels)
            {
                <option value="@item.id">@item.level</option>
            }
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Views/Case/Delete.cshtml
@model Case
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post" asp-action="Delete" asp-route-id="@Model.id">
    <div class="form-group">
        <label asp-for="requiredDate">requiredDate</label>
        <input asp-for="requiredDate" class="form-control">
    </div>
    <div class="form-group">
        <form action="Delete" method="post">
            <input type="hidden" asp-for="id" />
            <input type="submit" value="Confirm" class="btn btn-danger float-right mt-3" />
        </form>
</form>

Views/Case/Details.cshtml
@model Case
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>@Model.company?.name</h1>
<h2>@Model.requiredDate</h2>
<h2>Assessment Hours: @Model.assedHours</h2>

Views/Case/Edit.cshtml
@using FinalProject.ViewModel
@model EditCaseViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post" asp-action="Edit" asp-route-id="@Model.id">
    <div class="form-group">
        <label asp-for="reqiredDate">reqiredDate</label>
        <input asp-for="reqiredDate" class="form-control" placeholder="Enter reqiredDate">
    </div>
    <div class="form-group">
        <label asp-for="assedHours">assedHours</label>
        <input asp-for="assedHours" class="form-control" placeholder="Enter assedHours">
    </div>
    <div class="form-group">
        <select asp-for="companyId">
            <option value="">-- Select Company --</option>
            @foreach (var item in Model.companies)
            {
                <option value="@item.id">@item.name</option>
            }
        </select>
    </div>
    <div class="form-group">
        <select asp-for="dangerId">
            <option value="">-- Select DangerLevel --</option>
            @foreach (var item in Model.dangerLevels)
            {
                <option value="@item.id">@item.level</option>
            }
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Views/Case/Index.cshtml
@model IEnumerable<Case>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<a type="btn btn-success"
   asp-controller="Case" asp-action="Create" class="btn btn-outline-secondary" type="button">Create</a>
<div class="col-md-6">
    @foreach (var item in Model)
    {
        <div class="h-100 p-5 bg-body-tertiary border rounded-3">
            <h1>@item.company?.name</h1>
            <h2>@item.requiredDate</h2>

            <img class="card-img-bottom" height="250" width="250" src="~/css/images/case.png"/>
            <a type="btn btn-success"
               asp-controller="Case" asp-action="Details" asp-route-id="@item.id" class="btn btn-outline-secondary" type="button">View</a>
            <a type="btn btn-success"
               asp-controller="Case" asp-action="Edit" asp-route-id="@item.id" class="btn btn-outline-secondary" type="button">Edit</a>
            <a type="btn btn-success"
               asp-controller="Case" asp-action="Delete" asp-route-id="@item.id" class="btn btn-outline-secondary" type="button">Delete</a>
        </div>
    }
</div>