Controllers/LineOfBusinessController.cs
using FinalProject.Interfaces;
using FinalProject.Models;
using FinalProject.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers
{
    public class LineOfBusinessController : Controller
    {
        private readonly ILineOfBusinessRepository _lineOfBusinessRepository;

        public LineOfBusinessController(ILineOfBusinessRepository lineOfBusinessRepository)
        {
            _lineOfBusinessRepository = lineOfBusinessRepository;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<LineOfBusiness> lineOfBusinesses = await _lineOfBusinessRepository.GetAll();
            return View(lineOfBusinesses);
        }
        public async Task<IActionResult> Details(int id)
        {
            LineOfBusiness role = await _lineOfBusinessRepository.GetByIdAsync(id);
            return View(role);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateLineOfBuisnessViewModel lineVM)
        {
            if (ModelState.IsValid)
            {
                LineOfBusiness lineOfBusiness = new LineOfBusiness { title = lineVM.title};
                _lineOfBusinessRepository.Add(lineOfBusiness);
                return RedirectToAction("Index");
            }
            return View(lineVM);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            LineOfBusiness lineOfBusiness = await _lineOfBusinessRepository.GetByIdAsync(id);
            if (lineOfBusiness == null)
            {
                return View("Error");
            }
            EditLineOfBuisnessViewModel lineVm = new EditLineOfBuisnessViewModel
            {
                id = lineOfBusiness.id,
                title = lineOfBusiness.title
            };
            return View(lineVm);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditLineOfBuisnessViewModel lineVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed Edit");
                return View("Edit", lineVM);
            }
            LineOfBusiness lineOfBusiness = new LineOfBusiness
            {
                id = lineVM.id,
                title=lineVM.title
            };
            _lineOfBusinessRepository.Update(lineOfBusiness);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            LineOfBusiness lineDetails = await _lineOfBusinessRepository.GetByIdAsync(id);
            if (lineDetails == null)
            {
                return View("Error");
            }
            return View(lineDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteRole(int id)
        {
            LineOfBusiness lineDetails = await _lineOfBusinessRepository.GetByIdAsync(id);
            if (lineDetails  == null)
            {
                return View("Error");
            }
            _lineOfBusinessRepository.Delete(lineDetails);
            return RedirectToAction("Index");
        }
    }
}

Views/LineOfBusiness/Create.cshtml
@using FinalProject.ViewModel
@model CreateLineOfBuisnessViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post" asp-action="Create">
    <div class="form-group">
        <label asp-for="title">Title</label>
        <input asp-for="title" class="form-control" placeholder="Enter title">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Views/LineOfBusiness/Delete.cshtml
@model LineOfBusiness
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Are You Sure?</h2>
<form method="post" asp-action="Delete">
    <div class="form-group">
        <label asp-for="title">Title</label>
        <input asp-for="title" class="form-control" placeholder="Enter title">
    </div>
</form>
<div class="form-group">
    <form action="Delete" method="post">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Confirm" class="btn btn-danger float-right mt-3" />
    </form>
</div>

Views/LineOfBusiness/Details.cshtml
@model LineOfBusiness
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Title: </h1> <b>@Model.title</b>

Views/LineOfBusiness/Edit.cshtml
@using FinalProject.ViewModel
@model EditLineOfBuisnessViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post" asp-action="Edit">
    <div class="form-group">
        <label asp-for="title">Title</label>
        <input asp-for="title" class="form-control" placeholder="Enter title">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Views/LineOfBusiness/Index.cshtml
@model IEnumerable<LineOfBusiness>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<a type="btn btn-success"
   asp-controller="LineOfBusiness" asp-action="Create" class="btn btn-outline-secondary" type="button">Create</a>
<div class="col-md-6">
    @foreach (var item in Model)
    {
        <div class="h-100 p-5 bg-body-tertiary border rounded-3">
            <h2>@item.title</h2>
            <img class="card-img-bottom" height="250" width="250" src="~/css/images/lineofbusiness.jpg"/>
            <a type="btn btn-success"
               asp-controller="LineOfBusiness" asp-action="Details" asp-route-id="@item.id" class="btn btn-outline-secondary" type="button">View</a>
            <a type="btn btn-success"
               asp-controller="LineOfBusiness" asp-action="Edit" asp-route-id="@item.id" class="btn btn-outline-secondary" type="button">Edit</a>
            <a type="btn btn-success"
               asp-controller="LineOfBusiness" asp-action="Delete" asp-route-id="@item.id" class="btn btn-outline-secondary" type="button">Delete</a>
        </div>
    }
</div>