Models/DangerLevel.cs
using System.ComponentModel.DataAnnotations;

namespace FinalProject.Models
{
    public class DangerLevel
    {
        [Key]
        public int id { get; set; }
        [Required]
        public int level { get; set; }
        public string? description { get; set; }
        public string? title { get; set; }
    }
}

Controllers/DangerLevelController.cs
using FinalProject.Interfaces;
using FinalProject.Models;
using FinalProject.Repository;
using FinalProject.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers
{
    public class DangerLevelController : Controller
    {
        private readonly IDangerLevelRepository _dangerLevelRepository;

        public DangerLevelController(IDangerLevelRepository dangerLevelRepository)
        {
            _dangerLevelRepository = dangerLevelRepository;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<DangerLevel> dangerLevel = await _dangerLevelRepository.GetAll();
            return View(dangerLevel);
        }
        public async Task<IActionResult> Details(int id)
        {
            DangerLevel dangerLevel = await _dangerLevelRepository.GetByIdAsync(id);
            return View(dangerLevel);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateDangerLevelModel dangerLevelVM)
        {
            if (ModelState.IsValid)
            {
                DangerLevel dl = new DangerLevel
                {
                    level = dangerLevelVM.level,
                    description = dangerLevelVM.description,
                    title = dangerLevelVM.title
                };
                _dangerLevelRepository.Add(dl);
                return RedirectToAction("Index");
            }
            return View(dangerLevelVM);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            DangerLevel dangerLevel = await _dangerLevelRepository.GetByIdAsync(id);
            if (dangerLevel == null)
            {
                return View("Error");
            }
            EditDangerLevelModel dangerLevelVM = new EditDangerLevelModel
            {
                id = dangerLevel.id,
                level = dangerLevel.level,
                description = dangerLevel.description,
                title = dangerLevel.title
            };
            return View(dangerLevelVM);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int level, EditDangerLevelModel dangerLevelVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed Edit");
                return View("Edit", dangerLevelVM);
            }
            DangerLevel dangerLevel = new DangerLevel
            {
                id = dangerLevelVM.id,
                level = dangerLevelVM.level,
                description = dangerLevelVM.description,
                title = dangerLevelVM.title
            };
            _dangerLevelRepository.Update(dangerLevel);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            DangerLevel dangerLevelDetails = await _dangerLevelRepository.GetByIdAsync(id);
            if (dangerLevelDetails == null)
            {
                return View("Error");
            }
            return View(dangerLevelDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteRole(int id)
        {
            DangerLevel dangerLevelDetails = await _dangerLevelRepository.GetByIdAsync(id);
            if (dangerLevelDetails == null)
            {
                return View("Error");
            }
            _dangerLevelRepository.Delete(dangerLevelDetails);
            return RedirectToAction("Index");
        }
    }
}

Views/DangerLevel/Create.cshtml
@using FinalProject.ViewModel
@model CreateDangerLevelModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form method="post" asp-action="Create">
    <div class="form-group">
        <label asp-for="level">level</label>
        <input asp-for="level" class="form-control" placeholder="Enter level">
    </div>
    <div class="form-group">
        <label asp-for="title">Title</label>
        <input asp-for="title" class="form-control" placeholder="Enter title">
    </div>
    <div class="form-group">
        <label asp-for="description">description</label>
        <input asp-for="description" class="form-control" placeholder="description">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Views/DangerLevel/Delete.cshtml
@model DangerLevel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Are You Sure?</h2>
<form method="post" asp-action="Delete" asp-route-id="@Model.id">
    <div class="form-group">
        <label asp-for="id">id</label>
        <input asp-for="id" class="form-control" placeholder="Enter title">
    </div>
    <div class="form-group">
        <label asp-for="level">level</label>
        <input asp-for="level" class="form-control" placeholder="Enter title">
    </div>
    <div class="form-group">
        <label asp-for="title">Title</label>
        <input asp-for="title" class="form-control" placeholder="Enter title">
    </div>
    <div class="form-group">
        <label asp-for="description">Job Description</label>
        <input asp-for="description" class="form-control" placeholder="Enter description">
    </div>
</form>
<div class="form-group">
    <form action="Delete" method="post">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Confirm" class="btn btn-danger float-right mt-3" />
    </form>
</div>

Views/DangerLevel/Details.cshtml
@model DangerLevel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Level: </h1> <b>@Model.level</b>
<h2>Title: </h2> <b>@Model.title</b>
<h2>Description: </h2> <b>@Model.description</b>

Views/DangerLevel/Edit.cshtml
@using FinalProject.ViewModel
@model EditDangerLevelModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form method="post" asp-action="Edit" asp-route-id="@Model.id">
    <div class="form-group">
        <label asp-for="level">Level</label>
        <input asp-for="level" class="form-control" placeholder="Enter level">
    </div>
    <div class="form-group">
        <label asp-for="title">Title</label>
        <input asp-for="title" class="form-control" placeholder="Enter title">
    </div>
    <div class="form-group">
        <label asp-for="description">Job Description</label>
        <input asp-for="description" class="form-control" placeholder="Enter description">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Views/DangerLevel/Index.cshtml
@model IEnumerable<DangerLevel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<a type="btn btn-success"
   asp-controller="DangerLevel" asp-action="Create" class="btn btn-outline-secondary" type="button">Create</a>
<div class="col-md-6">
    @foreach (var item in Model)
    {
        <div class="h-100 p-5 bg-body-tertiary border rounded-3">
            <h2>@item.level</h2>
            <p>@item.title</p>
            <img class="card-img-bottom" height="250" width="250" src="~/css/images/img1.jpg" />
            <a type="btn btn-success"
               asp-controller="DangerLevel" asp-action="Details" asp-route-id="@item.id" class="btn btn-outline-secondary" type="button">View</a>
            <a type="btn btn-success"
               asp-controller="DangerLevel" asp-action="Edit" asp-route-id="@item.id" class="btn btn-outline-secondary" type="button">Edit</a>
            <a type="btn btn-success"
               asp-controller="DangerLevel" asp-action="Delete" asp-route-id="@item.id" class="btn btn-outline-secondary" type="button">Delete</a>
        </div>
    }
</div>